name: Publish NPM Private Package
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Tag version (ex: 1.0.1)'
        required: true

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      GITHUB_TOKEN: ${{ secrets.ORGANIZATION_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --pure-lockfile --production=false
      - name: Update Tag
        run: |
          git remote set-url origin https://github-actions:${{secrets.ORGANIZATION_TOKEN}}@github.com/$GITHUB_REPOSITORY
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          npm version ${{ github.event.inputs.release_version }}
          git push origin main
          git push origin v${{ github.event.inputs.release_version }}
      - name: Publish
        run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}